[workspace]
name = "tsumo-mojo"
channels = ["conda-forge", "https://conda.modular.com/max-nightly/"]
platforms = ["linux-64"]

[dependencies]
mojo = "==1.1.0.dev2026083005"
python = ">=3.12,<3.15"

[pypi-dependencies]
linkify-it-py = "==2.0.3"
markdown-it-py = "==4.0.0"
mdit-py-plugins = "==0.5.0"
pillow = "==12.1.1"
quickjs = "==1.19.4"

[tasks]
format = "mojo format -l 100 mojo"
